import Head from "next/head";
import "antd/dist/antd.css";
import { useSelector } from "react-redux";
import SignupForm from "../components/login/SignupForm";
import SpinLoading from "../components/spin/SpinLoading";
import withAuthPublic from "../components/withAuthPublic";

const Home = () => {
  const { loggedIn } = useSelector((state) => state.logged);

  if (loggedIn) {
    return (
      <>
        <SpinLoading />
      </>
    );
  } else {
    return (
      <div>
        <Head>
          <title>Prueba técnica</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <SignupForm />
        </main>
      </div>
    );
  }
};

export default withAuthPublic(Home);
