import Head from "next/head";
import "antd/dist/antd.css";
import SignupForm from "../components/login/SignupForm";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Prueba técnica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SignupForm />
      </main>
    </div>
  );
}
